"""Initial commit

Revision ID: 85156b624a62
Revises: 
Create Date: 2022-07-01 14:14:23.670880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85156b624a62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_owners',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('cnh', sa.String(length=11), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('opportunity', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('owner_id'),
    sa.UniqueConstraint('cnh')
    )
    op.create_table('tb_cars',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=6), nullable=False),
    sa.Column('model', sa.String(length=11), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['tb_owners.owner_id'], ),
    sa.PrimaryKeyConstraint('car_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_cars')
    op.drop_table('tb_owners')
    # ### end Alembic commands ###
